# apiVersion: storage.gcp.upbound.io/v1beta1
# kind: Bucket
# metadata:
#   name: sai-temp-034
#   namespace: default
#   annotations:
#     crossplane.io/external-name: sai-temp-034
# spec:
#   forProvider:
#     location: US
#     storageClass: STANDARD
#   providerConfigRef:
#     name: default
