apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-store
spec:
  provider:
    gcpsm:
      projectID: platformproject-481722
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a # Your cluster zone
          clusterName: omnitrix-cluster # Your cluster name
          serviceAccountRef:
            name: external-secrets # The KSA name
            namespace: external-secrets # The namespace
