apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-sql
spec:
  package: xpkg.upbound.io/upbound/provider-gcp-sql:v2.2.0 # Latest stable
  runtimeConfigRef:
    name: gcp-config
