apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  # âœ… Using the v2-compatible release

  #3package: xpkg.upbound.io/crossplane-contrib/provider-upjet-gcp:v1.14.0

  package: xpkg.upbound.io/upbound/provider-gcp-cloud:v2.4.0
