## this is for the K8 Service aaccoount crossplne-gcp is linked to Google cloud service account
## as crossplne-provider@platformproject-481722.iam.gserviceaccount.com

apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-gcp
  namespace: crossplane-system
  annotations:
    iam.gke.io/gcp-service-account: crossplane-provider@platformproject-481722.iam.gserviceaccount.com
