## backaste takes form inputs (paramets), maps them to values in fetch:template and replaces Sanjay-sreem with the value entered by the user in the form

## mean the backstage directly (fetch:template) step copies everything inside the skeleton folder & process placeholders like Sanjay-sreem
apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: Sanjay-sreem
  namespace: default
  annotations:
    crossplane.io/external-name: Sanjay-sreem
spec:
  forProvider:
    location: US
    storageClass: STANDARD
  providerConfigRef:
    name: default
